stages:
  - test

test:
  stage: test
  image: python:3.9
  before_script:
    - apt-get update && apt-get install -y default-jdk
    - export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
    - export PATH="$JAVA_HOME/bin:$PATH"
    - pip install pytest pyspark
  script:
    - pytest tests/
  tags:
    - docker
