FROM python:3.9

# Install Java
RUN apt-get update && apt-get install -y default-jdk

# Set JAVA_HOME
ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
ENV PATH="$JAVA_HOME/bin:$PATH"

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install pyspark pytest

# Set working directory
WORKDIR /app
